"""add worker assignment to complaints

Revision ID: 090d4aeb59ce
Revises: ab27d243564c
Create Date: 2026-10-05 01:38:21.856703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090d4aeb59ce'
down_revision: Union[str, Sequence[str], None] = 'ab27d243564c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'complaints',
        sa.Column(
            'assigned_worker_id',
            sa.Integer(),
            nullable=True
        )
    )

    op.create_foreign_key(
        'fk_complaints_assigned_worker_id',
        'complaints',
        'users',
        ['assigned_worker_id'],
        ['id']
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'assigned_worker_id')
    # ### end Alembic commands ###
