"""link recovery observations to interventions

Revision ID: 951b3b8c680f
Revises: dc1872afe745
Create Date: 2026-10-06 20:57:38.257303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951b3b8c680f'
down_revision: Union[str, Sequence[str], None] = 'dc1872afe745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_observations', sa.Column('intervention_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recovery_observations', 'interventions', ['intervention_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'recovery_observations', type_='foreignkey')
    op.drop_column('recovery_observations', 'intervention_id')
    # ### end Alembic commands ###
