"""add intervention and recovery observation tables

Revision ID: dc1872afe745
Revises: 090d4aeb59ce
Create Date: 2026-10-06 19:56:54.121354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1872afe745'
down_revision: Union[str, Sequence[str], None] = '090d4aeb59ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expected_impact_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    op.create_index(op.f('ix_interventions_intervention_id'), 'interventions', ['intervention_id'], unique=True)
    op.create_table('recovery_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('observation_status', sa.String(), nullable=False),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_observations_id'), 'recovery_observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_observations_id'), table_name='recovery_observations')
    op.drop_table('recovery_observations')
    op.drop_index(op.f('ix_interventions_intervention_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_table('interventions')
    # ### end Alembic commands ###
